### ISSUE TITLE
This crashes in next.js because you are trying to use "window"

### ISSUE THREAD

**Issue by hassanzadeh** [twilio/twilio-video-processors.js#32]
This does not work with next.js framework because you are using "window" somewhere in your code and that cannot be rendered on the server:
index.js?20a9:314 Uncaught     at isBrowserSupported (file:///Users/hh/Workspaces/mb/node_modules/@twilio/video-processors/es5/utils/support.js:8:5)
    at Object.<anonymous> (file:///Users/hh/Workspaces/mb/node_modules/@twilio/video-processors/es5/utils/support.js:23:23)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (file:///Users/hh/Workspaces/mb/node_modules/@twilio/video-processors/es5/index.js:21:17)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
getNodeError @ nodeStackFrames.js?aca3:40
eval @ index.js?20a9:313
setTimeout (async)
_callee$ @ index.js?20a9:301
tryCatch @ runtime.js?96cf:63
invoke @ runtime.js?96cf:293
eval @ runtime.js?96cf:118
asyncGeneratorStep @ index.js?20a9:28
_next @ index.js?20a9:46
Promise.then (async)
asyncGeneratorStep @ index.js?20a9:37
_next @ index.js?20a9:46
eval @ index.js?20a9:51
eval @ index.js?20a9:43
_initNext @ index.js?20a9:363
initNext @ index.js?20a9:366
eval @ next-dev.js?3346:38
./node_modules/next/dist/client/next-dev.js @ main.js?ts=1635297231978:600
options.factory @ webpack.js?ts=1635297231978:658
__webpack_require__ @ webpack.js?ts=1635297231978:37
__webpack_exec__ @ main.js?ts=1635297231978:1399
(anonymous) @ main.js?ts=1635297231978:1400
webpackJsonpCallback @ webpack.js?ts=1635297231978:1241
(anonymous) @ main.js?ts=1635297231978:9

**Comment by charliesantos** [comment]
This has been fixed in 1.0.2.

**Comment by hassanzadeh** [comment]
Thanks @charliesantos ,
Also do you know if it is possible (in Next js) to add the assets under node_modules to the list of  public directory ? I know with node_js we have can use express.static (if I recall) to do that.

Thanks

**Comment by hassanzadeh** [comment]
I'm seeing this error in the console, what is it about?

![image](https://user-images.githubusercontent.com/13952413/140629451-a6c1b59f-4cb0-4272-9e12-9a428d4dc1ab.png)

THanks

**Comment by charliesantos** [comment]
@hassanzadeh how are you including or loading the tflite-simd-1-0-0.js file?
